In [1]:
import mne
mne.set_log_level('error')
from pathlib import Path
import matplotlib
import matplotlib.pyplot as plt
import glob
from functions import *
import numpy as np
matplotlib.use('TkAgg')

### Loading the data

In [2]:
data_path = "/Users\sunnivlf\Documents/Data Set Alcohol Detector/Subjects"
p_id = "/" + "sub-P019" + "/" + "ses-S002" + "/" + "sub-P019_ses-S002_task-Default_run-005"
raw = mne.io.read_raw_fif(data_path + "/" + p_id + "_eeg.fif", preload=True)

Plotting the elctrode placement on the scalp

In [3]:
raw.plot_sensors(show_names=True);

### Filtering the data
Highpass filtering is included to remove drifting of the signal, while lowpass filtering will remove power line noise


In [9]:
low_cut = 0.1 
hi_cut  = 30
raw_filt = raw.copy().filter(low_cut, hi_cut)
raw_filt.compute_psd(fmax=125).plot(picks="data", exclude="bads");
raw_filt.plot(highpass=0.1, lowpass=30, duration=200)

<MNEBrowseFigure size 1920x1137 with 4 Axes>

Choose one channel to use for this experiment. Fp2 is one of the frontal electrodes. The data and time is extracted from the filtered raw data, as numpy arrays.

In [10]:
picks = mne.pick_channels(ch_names = ['Fp2'], include=['Fp2'])
data, time = raw_filt[picks, :]  

The signal is visulaized using matplotlib.

In [11]:
plt.figure(figsize=(10, 4))
plt.plot(time, data[0])
plt.xlabel('Time (s)')
plt.ylabel('EEG Amplitude')
plt.title('EEG Data for Fp2 Channel')
plt.grid(True)
plt.tight_layout()
plt.show()

In [12]:
num_samples = len(data[0])
sample_rate = raw.info['sfreq']
fft(data[0], num_samples, sample_rate)

(array([ 0.        ,  0.00231917,  0.00463835, ..., -0.00695752,
        -0.00463835, -0.00231917]),
 array([0.05004837, 0.05196872, 0.04583062, ..., 0.04063419, 0.04583062,
        0.05196872]))

In [13]:
plot_stft(data[0], sample_rate)

(array([  0.  ,   0.25,   0.5 ,   0.75,   1.  ,   1.25,   1.5 ,   1.75,
          2.  ,   2.25,   2.5 ,   2.75,   3.  ,   3.25,   3.5 ,   3.75,
          4.  ,   4.25,   4.5 ,   4.75,   5.  ,   5.25,   5.5 ,   5.75,
          6.  ,   6.25,   6.5 ,   6.75,   7.  ,   7.25,   7.5 ,   7.75,
          8.  ,   8.25,   8.5 ,   8.75,   9.  ,   9.25,   9.5 ,   9.75,
         10.  ,  10.25,  10.5 ,  10.75,  11.  ,  11.25,  11.5 ,  11.75,
         12.  ,  12.25,  12.5 ,  12.75,  13.  ,  13.25,  13.5 ,  13.75,
         14.  ,  14.25,  14.5 ,  14.75,  15.  ,  15.25,  15.5 ,  15.75,
         16.  ,  16.25,  16.5 ,  16.75,  17.  ,  17.25,  17.5 ,  17.75,
         18.  ,  18.25,  18.5 ,  18.75,  19.  ,  19.25,  19.5 ,  19.75,
         20.  ,  20.25,  20.5 ,  20.75,  21.  ,  21.25,  21.5 ,  21.75,
         22.  ,  22.25,  22.5 ,  22.75,  23.  ,  23.25,  23.5 ,  23.75,
         24.  ,  24.25,  24.5 ,  24.75,  25.  ,  25.25,  25.5 ,  25.75,
         26.  ,  26.25,  26.5 ,  26.75,  27.  ,  27.25,  27.5 , 